fix: change dropin name to drop-in
commerce-docs/microsite-commerce-storefront pull request #105
Opened 2024-11-08 14:46 UTC by bdenham

This PR changes the spelling of "dropin" to the approved spelling: "drop-in".

Mike Ordoyne from the Brand Strategy team approved the naming convention which should include a hyphen: “drop-in.”

2024-11-08 15:03 UTC, jeff-matthews reviewed
According to the wiki:

- "Drop-in components" is preferred over "DropIns."
the name structure [Functional Name] Drop-in is correct for individual drop-ins. Acronyms should not be used as part of the name. (from Branding)
- "Cart drop-in component", once established, can be written as, "the cart component" or "the cart").

2024-11-08 15:07 UTC, bdenham commented
Yep, I’ll do another sweep.

2024-11-11 23:37 UTC, bdenham commented
I removed capitalization and created shorthand entries for cart, checkout, and product details drop-ins  as prescribed in the wiki.

2024-11-12 15:53 UTC, jeff-matthews reviewed
I started making some suggestions, but there are too may files. I don't think we should use "drop-in" standalone. My understanding is that it should be "drop-in component".

2024-11-12 15:53 UTC, jeff-matthews commented on README.md
> +   description: Learn about slots and how to use them to customize drop-ins.
```suggestion
   description: Learn about slots and how to use them to customize drop-in components.
```

2024-11-12 15:53 UTC, jeff-matthews commented on README.md
> +   description: Learn about slots and how to use them to customize drop-ins.
```suggestion
   description: Learn about slots and how to use them to customize drop-in components.
```

2024-11-12 15:53 UTC, jeff-matthews commented on _drafts/_dropins.mdx
> +description: Learn how drop-ins define all of our Commerce storefronts.
```suggestion
description: Learn how drop-in components define all of our Commerce storefronts.
```

2024-11-12 15:53 UTC, jeff-matthews commented on _drafts/_dropins.mdx
> +## Drop-ins are the building blocks of our storefronts
```suggestion
## Drop-in components are the building blocks of our storefronts
```

2024-11-12 15:53 UTC, jeff-matthews commented on _dropin-templates/SidebarConfiguration.mjs
> +// Use these items to create a TOC entry for a new drop-in:
```suggestion
// Use these items to create a TOC entry for a new drop-in component:
```

2024-11-12 15:53 UTC, jeff-matthews commented on _dropin-templates/dropin-anatomy.mdx
> +description: Learn about the purpose and parts of the DROPIN_NAME drop-in.
```suggestion
description: Learn about the purpose and parts of the DROPIN_NAME drop-in component.
```

2024-11-12 15:53 UTC, jeff-matthews commented on _dropin-templates/dropin-anatomy.mdx
> +{/* Replace `placeholder.webp` with a diagram of the drop-in identifying all its parts: Containers, slots, components, CSS styles, and design tokens. */}
```suggestion
{/* Replace `placeholder.webp` with a diagram of the drop-in component identifying all its parts: Containers, slots, components, CSS styles, and design tokens. */}
```

2024-11-12 15:53 UTC, jeff-matthews commented on _dropin-templates/dropin-anatomy.mdx
> +The DROPIN_NAME drop-in provides the following customizable elements:
```suggestion
The DROPIN_NAME drop-in component provides the following customizable elements:
```

2024-11-13 10:10 UTC, bdenham commented
@jeff-matthews I added another pass to changing the standalone "drop-in" instances to "drop-in component"

2024-11-13 16:33 UTC, jeff-matthews requested changes
@bdenham, I created #113 to address some of the issues I was still seeing in this PR.

2024-11-13 18:28 UTC, jeff-matthews approved these changes

2024-11-13 19:45 UTC, merged