Docsite updates
commerce-docs/microsite-commerce-storefront pull request #49
Opened 2024-09-11 20:27 UTC by bdenham

This PR consolidates the accumulation of the updates from PR #41 that are not related to the template files in that PR.

2024-09-11 21:44 UTC, jeff-matthews requested changes
If the base branch was an integration branch and not `develop`, I wouldn't have flagged the links to empty topics in the sidenav.

If the goal is to merge with mainline and deploy to prod, we need to remove those links first. I'm ok including the empty files themselves, but it's still not really a best practice across our doc repos and should be avoided.

2024-09-11 21:44 UTC, jeff-matthews commented on src/content/docs/dropins/all/installing.mdx
> +title: Installing dropins
The body content is still specific to PDP and needs to be genericized.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +            label: 'Introduction',
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +            label: 'Anatomy of a dropin',
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +            label: 'Localizing dropins',
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +            label: 'Enriching dropins',
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
>                { label: 'PDP Styles', link: '/dropins/product-details/pdp-styles/' },
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +              { label: 'PDP Data & Events', link: '/dropins/product-details/pdp-data-events/' },
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +              { label: 'How to change labels', link: '/dropins/product-details/change-labels/' },
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +              { label: 'How to override slots', link: '/dropins/product-details/override-slots/' },
We shouldn't include links to empty files in the sidenav.

2024-09-11 21:44 UTC, jeff-matthews commented on astro.config.mjs
> +              { label: 'How to add enrichment', link: '/dropins/product-details/add-enrichment/' },
We shouldn't include links to empty files in the sidenav.

2024-09-12 01:50 UTC, bdenham commented
@jeff-matthews Updated

2024-09-12 13:11 UTC, jeff-matthews reviewed
A couple more comments related to the sidenav.

I think this PR is still attempting to do some template-style restructuring in addition to updating components/styles. It's a little confusing exactly what we're trying to accomplish with this.

2024-09-12 13:11 UTC, jeff-matthews commented on astro.config.mjs
> -              { label: 'PDP Styles', link: '/dropins/product-details/pdp-styles/' },
The [PDP Styles](https://experienceleague.adobe.com/developer/commerce/storefront/dropins/product-details/pdp-styles/) page looks like it has good content. I think we should keep it in the sidenav.

2024-09-12 13:11 UTC, jeff-matthews commented on astro.config.mjs
> -              { label: 'PDP Installation', link: '/dropins/product-details/pdp-installation/' },
I'm not sure hiding the [PDP Installation](https://experienceleague.adobe.com/developer/commerce/storefront/dropins/product-details/pdp-installation/) page from the sidenav is the right move. At least not until we have a generic installation page under `dropins/all/installing.mdx`.

Also, the [Cart Installation](https://experienceleague.adobe.com/developer/commerce/storefront/dropins/cart/cart-installation/) page is still displayed in the sidenav in this branch, which creates inconsistency.

2024-09-17 20:25 UTC, closed without merging