USF-1329: Checkout functions
commerce-docs/microsite-commerce-storefront pull request #52
Opened 2024-09-16 19:41 UTC by jeff-matthews

This pull request (PR) adds the following information for the checkout dropin functions:

- Description
- Returns (when applicable)
- Usage

A majority of these functions either 1) transforms the API response and return a promise that resolves to the transformed data fetched from the API. I need some help understanding how we want to represent that in each case.

See USF-1329 for more information.

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +Uses a utility function to send an [`estimateShippingMethodsMutation`](https://developer.adobe.com/commerce/webapi/graphql-api/index.html#mutation-estimateShippingMethods) request to the Adobe Commer
This line belongs in the overview section. The next few functions have the cross reference there.

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +Retrieves a list of EAV attributes associated with customer register and customer address frontend forms from the Adobe Commerce GraphQL API using the [`attributesForm`](https://developer.adobe.com/c
```suggestion
Uses the [`attributesForm`](https://developer.adobe.com/commerce/webapi/graphql/schema/attributes/queries/attributes-form/) query to retrieve a list of EAV attributes associated with customer and customer address frontend forms.
```

If you choose to keep the sentence structure as is, note that I deleted "register". Customers can edit and register their settings.

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +Fetches and prepares the necessary data for the checkout process. It uses the `getCart` and `getCustomer` functions to fetch the cart and customer data from the Adobe Commerce GraphQL API.
Add a link to the `getCart` and `getCustomer` functions. Since this function doesn't retrieve GraphQL directly, I think I'd leave that out.

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +type Customer = {
`Customer` should be listed first, IMHO.

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +A value of `true` indicates that the email address is available and the customer can use the email address to create an account.
As of 2.4.7, the default value is always true, for security reasons. I don't think it's necessary to explain why here, but maybe say something like "refer to the query documentation for implementation details."

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +    state: 'NY',
`state` is not part of the schema. It should be `region` or maybe a `region` object

2024-09-17 20:06 UTC, keharper commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +    region: {
`region` looks correct here

2024-09-18 10:48 UTC, mcocapiza requested changes

2024-09-18 10:48 UTC, mcocapiza commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +placeOrder('4L7E1H0muABuggqWxbzBCBWoeG0rNxDh');
`placeOrder()` API is without params (I guess mdx file was not updated correctly).

2024-09-18 10:48 UTC, mcocapiza commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +Handles the process of placing an order in the checkout system using the [`placeOrder`](https://developer.adobe.com/commerce/webapi/graphql/schema/cart/mutations/place-order/) Adobe Commerce GraphQL
Also you could mention this API is publishing the `'place-order'` [Adobe Commerce Event](https://github.com/adobe/commerce-events/blob/main/examples/events/place-order.md) within the [order](https://github.com/adobe/commerce-events/blob/main/packages/storefront-events-sdk/src/types/schemas/order.ts) and [shoppingCart](https://github.com/adobe/commerce-events/blob/main/packages/storefront-events-sdk/src/types/schemas/shoppingCart.ts) contexts to the ACDL ([Adobe Client Data Layer](https://github.com/adobe/adobe-client-data-layer)).

2024-09-18 10:48 UTC, mcocapiza commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +It takes the following parameters:
We refactored the input parameters to keep compatibility with the mutation as follow:
`setBillingAddress({input: BillingAddressInput})`
...where 
```
BillingAddressInput {
  address?: AddressInput;
  customer_address_id?: number;
  same_as_shipping?: boolean;
  use_for_shipping?: boolean;
}
```
Then an example could be:
```
setBillingAddress({
  input: {
    address: {
      firstname: 'John',
      lastname: 'Doe',
      street: ['123 Main St', 'Apt 1'],
      city: 'New York',
      postcode: '10001',
      country_code: 'US',
      telephone: '555-555-5555',
    },
    same_as_shipping: false,
  }
});
```
I guess the mdx file is not up-to-date.

2024-09-18 10:48 UTC, mcocapiza commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +- `cart_id`: The unique ID of the cart object.
The only param is `email` (cart_id is got from an internal state).

2024-09-18 10:48 UTC, mcocapiza commented on src/content/docs/dropins/checkout/checkout-functions.mdx
> +setGuestEmailOnCart({
The example should be:
`setGuestEmailOnCart('test@example.com')`

2024-09-18 10:53 UTC, mcocapiza commented
Hi @jeff-matthews, overall looks good to me, but please note we are refactoring code (splitting containers, we are trying to share the AddressForm from the Account dropin, etc), so probably in few weeks there will be changes on the API functions (removing, modifying, etc).

2024-09-18 15:02 UTC, jeff-matthews commented
Thanks for the review @mcocapiza & @keharper.

I pushed changes to address your comments.

2024-09-19 10:21 UTC, mcocapiza approved these changes

2024-09-24 22:32 UTC, jeff-matthews commented
@bdenham,

I refactored according to your revised template that we discussed in Slack. Please review by tomorrow.

2024-09-27 01:05 UTC, bdenham commented
@jeff-matthews I redid the first function on the page that needs to be replicated for all the other functions. Then we can merge. Thanks!

2024-09-27 01:06 UTC, bdenham approved these changes
Use the first function layout pattern to apply to all the others, naming omitting the Signature headings.

2024-09-27 01:49 UTC, closed without merging

2024-09-27 01:52 UTC, jeff-matthews commented
Thanks @bdenham. I'm going to re-create the latest changes from this branch and clean up the commits. I'll create a new PR ofter that.