USF-1327: Checkout containers (redux)
commerce-docs/microsite-commerce-storefront pull request #71
Opened 2024-10-01 19:59 UTC by jeff-matthews

This pull request (PR) documents Checkout container configuration options based on the [doc template](https://github.com/commerce-docs/microsite-commerce-storefront/blob/develop/_dropin-templates/dropin-containers.mdx?plain=1) for dropin containers.

Options and descriptions are based on the prop interfaces defined for each component in the source code. 

## TODO

- [x] Articulate potential/practical use case(s) for each container
- [ ] Provide an example configuration that covers all containers
- [ ] Provide an example of configuring options on a container w/ before and after screenshot of boilerplate and modified boilerplate

## Review build

_TBD_

2024-11-07 17:39 UTC, mcocapiza requested changes
Also, you need to add a couple of more containers:
- BillToShippingAddress => Checkbox to decide if the billing address will be the same as the shipping address, otherwise the billing address form is shown

**example**:

```
import BillToShippingAddress from '@dropins/storefront-checkout/containers/BillToShippingAddress.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $billToShipping = checkoutFragment.querySelector(
  '.checkout__bill-to-shipping'
);

CheckoutProvider.render(BillToShippingAddress, {
  hideOnVirtualCart: true,
  onChange: (checked) => {
    $billingForm.style.display = checked ? 'none' : 'block';

    if (!checked && billingFormRef.current) {
      const isDataValid = billingFormRef.current.handleValidationSubmit();

      setAddressOnCart(
        { data: billingFormRef.current.formData, isDataValid },
        checkoutApi.setBillingAddress
      );
    }
  },
})($billToShipping),
```

- OrderConfirmationHeader => Once the order is placed, a new order confirmation page is shown with the order details. This container also has the "Create an account" button (Sign-up) in case the guest user wanted to create an account

**example**:

```
import OrderConfirmationHeader from '@dropins/storefront-checkout/containers/OrderConfirmationHeader.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $orderConfirmationHeader = orderConfirmationFragment.querySelector(
  '.order-confirmation__header'
);

CheckoutProvider.render(OrderConfirmationHeader, {
  orderData,
  onSignUpClick,
})($orderConfirmationHeader);
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/estimate-shipping.mdx
> +/>
Although `EstimateShipping` is a checkout container, it's a bit special. We had to create this one to overwrite the `EstimateShipping` defined into the Storefront Cart dropin. Whereas the `EstimateShipping` defined into the Storefront Cart dropin is editable, the `EstimateShipping` defined into the Checkout dropin is readonly.
Initially it shows the estimate shipping costs, but once the customer has introduced a shipping address and a shipping method is selected, then it shows the real shipping cost.
You can see the estimate shipping information inside of the `OrderSummary` container (comming from the Storefront Cart dropin)... so it only makes sense to use it as slot of the `OrderSummary` container.

**example**:

```
import { OrderSummary } from '@dropins/storefront-cart/containers/OrderSummary.js';
import { render as CartProvider } from '@dropins/storefront-cart/render.js';

const $orderSummary = checkoutFragment.querySelector(
  '.checkout__order-summary'
);

CartProvider.render(OrderSummary, {
  slots: {
    EstimateShipping: (esCtx) => {
      const estimateShippingForm = document.createElement('div');
      CheckoutProvider.render(EstimateShipping)(estimateShippingForm);
      esCtx.appendChild(estimateShippingForm);
    },
  },
})($orderSummary),
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/login-form.mdx
> +/>
`LoginForm` uses the `AuthCombine` container defined into the Storefront Auth dropin.

**example**:

```
import AuthCombine from '@dropins/storefront-auth/containers/AuthCombine.js';
import { render as AuthProvider } from '@dropins/storefront-auth/render.js';

import LoginForm from '@dropins/storefront-checkout/containers/LoginForm.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $login = checkoutFragment.querySelector('.checkout__login');

CheckoutProvider.render(LoginForm, {
  name: LOGIN_FORM_NAME,
  onSignInClick: async (initialEmailValue) => {
    const signInForm = document.createElement('div');

    AuthProvider.render(AuthCombine, {
      signInFormConfig: {
        renderSignUpLink: true,
        initialEmailValue,
        onSuccessCallback: () => {
          displayOverlaySpinner();
        },
      },
      signUpFormConfig: {},
      resetPasswordFormConfig: {},
    })(signInForm);

    showModal(signInForm);
  },
  onSignOutClick: () => {
    authApi.revokeCustomerToken();
  },
})($login),
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/out-of-stock.mdx
> +/>
**example**:

```
import OutOfStock from '@dropins/storefront-checkout/containers/OutOfStock.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $outOfStock = checkoutFragment.querySelector('.checkout__out-of-stock');

CheckoutProvider.render(OutOfStock, {
  routeCart: () => '/cart',
  onCartProductsUpdate: (items) => {
    cartApi.updateProductsFromCart(items).catch(console.error);
  },
})($outOfStock),
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/payment-methods.mdx
> +/>
**example**:

```
import PaymentMethods from '@dropins/storefront-checkout/containers/PaymentMethods.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $paymentMethods = checkoutFragment.querySelector(
  '.checkout__payment-methods'
);

CheckoutProvider.render(PaymentMethods)($paymentMethods),
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/place-order.mdx
> +/>
`PlaceOrder` container accepts a function as a prop to be used to perform some validations (like forms, etc):

```handleValidation?: () => boolean;```

**example**:

```
import PlaceOrder from '@dropins/storefront-checkout/containers/PlaceOrder.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $placeOrder = checkoutFragment.querySelector('.checkout__place-order');

CheckoutProvider.render(PlaceOrder, {
  handleValidation: () => {
    let success = true;
    const forms = document.forms;

    const loginForm = forms[LOGIN_FORM_NAME];

    if (loginForm) {
      success = loginForm.checkValidity();
      if (!success) scrollToElement($login);
    }

    const shippingForm = forms[SHIPPING_FORM_NAME];

    if (
      success &&
      shippingFormRef.current &&
      shippingForm &&
      shippingForm.checkVisibility()
    ) {
      success = shippingFormRef.current.handleValidationSubmit(false);
    }

    const billingForm = forms[BILLING_FORM_NAME];

    if (
      success &&
      billingFormRef.current &&
      billingForm &&
      billingForm.checkVisibility()
    ) {
      success = billingFormRef.current.handleValidationSubmit(false);
    }

    return success;
  },
  onPlaceOrder: async () => {
    displayOverlaySpinner();

    try {
      await checkoutApi.placeOrder();
    } catch (error) {
      console.error(error);
      throw error;
    } finally {
      removeOverlaySpinner();
    }
  },
})($placeOrder),
]);
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/server-error.mdx
> +/>
**example**:

```
import ServerError from '@dropins/storefront-checkout/containers/ServerError.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $serverError = checkoutFragment.querySelector(
  '.checkout__server-error'
);

CheckoutProvider.render(ServerError, {
  onRetry: () => {
    $content.classList.remove('checkout__content--error');
  },
  onServerError: () => {
    $content.classList.add('checkout__content--error');
  },
})($serverError),
```

2024-11-07 17:39 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/shipping-methods.mdx
> +/>
**example**:

```
import ShippingMethods from '@dropins/storefront-checkout/containers/ShippingMethods.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $delivery = checkoutFragment.querySelector('.checkout__delivery');

CheckoutProvider.render(ShippingMethods, {
  hideOnVirtualCart: true,
  onCheckoutDataUpdate: () => {
    cartApi.refreshCart().catch(console.error);
  },
})($delivery),
```

2024-11-08 12:14 UTC, mcocapiza commented on src/content/docs/dropins/checkout/containers/error-banner.mdx
> +/>
Please remove this block... we are not going to use it.

2024-11-08 15:31 UTC, jeff-matthews commented
Thanks @mcocapiza. I addressed your feedback and added the additional containers (`BillToShippingAddress` and `OrderConfirmationHeader`).

Will you please provide a code sample for the `MergedCartBanner` container?

2024-11-08 17:22 UTC, jeff-matthews commented
I found a simple example in Slack. I'll push changes in a moment.

2024-11-11 08:10 UTC, mcocapiza commented
- MergedCartBanner => When the customer performs a "Sign-In" action, if he/she/it had a previous cart within products inserted, then a banner is shown informing the current items added into the guest cart and the items recovered from a previous customer cart will be merged. 

**example**:

```
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $mergedCartBanner = checkoutFragment.querySelector(
  '.checkout__merged-cart-banner',
);

CheckoutProvider.render(MergedCartBanner)($mergedCartBanner),
```

2024-11-11 10:40 UTC, mcocapiza commented
Please update the `EstimateShipping` example (I missed to import the `EstimateShipping` container from Checkout dropin):

```
import { OrderSummary } from '@dropins/storefront-cart/containers/OrderSummary.js';
import { render as CartProvider } from '@dropins/storefront-cart/render.js';
import EstimateShipping from '@dropins/storefront-checkout/containers/EstimateShipping.js';

const $orderSummary = checkoutFragment.querySelector(
  '.checkout__order-summary'
);

CartProvider.render(OrderSummary, {
  slots: {
    EstimateShipping: (esCtx) => {
      const estimateShippingForm = document.createElement('div');
      CheckoutProvider.render(EstimateShipping)(estimateShippingForm);
      esCtx.appendChild(estimateShippingForm);
    },
  },
})($orderSummary),

```

2024-11-11 11:03 UTC, mcocapiza commented
Please update the OutOfStock example (I missed to import the cartApi from Cart dropin):

```
import * as cartApi from '@dropins/storefront-cart/api.js';
import OutOfStock from '@dropins/storefront-checkout/containers/OutOfStock.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $outOfStock = checkoutFragment.querySelector('.checkout__out-of-stock');

CheckoutProvider.render(OutOfStock, {
  routeCart: () => '/cart',
  onCartProductsUpdate: (items) => {
    cartApi.updateProductsFromCart(items).catch(console.error);
  },
})($outOfStock),
```

2024-11-11 11:12 UTC, mcocapiza commented
Please update the `PlaceOrder` example (I missed to import the `checkoutApi` from Checkout dropin):

```
import * as checkoutApi from '@dropins/storefront-checkout/api.js';
import PlaceOrder from '@dropins/storefront-checkout/containers/PlaceOrder.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $placeOrder = checkoutFragment.querySelector('.checkout__place-order');

CheckoutProvider.render(PlaceOrder, {
  handleValidation: () => {
    let success = true;
    const forms = document.forms;

    const loginForm = forms[LOGIN_FORM_NAME];

    if (loginForm) {
      success = loginForm.checkValidity();
      if (!success) scrollToElement($login);
    }

    const shippingForm = forms[SHIPPING_FORM_NAME];

    if (
      success &&
      shippingFormRef.current &&
      shippingForm &&
      shippingForm.checkVisibility()
    ) {
      success = shippingFormRef.current.handleValidationSubmit(false);
    }

    const billingForm = forms[BILLING_FORM_NAME];

    if (
      success &&
      billingFormRef.current &&
      billingForm &&
      billingForm.checkVisibility()
    ) {
      success = billingFormRef.current.handleValidationSubmit(false);
    }

    return success;
  },
  onPlaceOrder: async () => {
    displayOverlaySpinner();

    try {
      await checkoutApi.placeOrder();
    } catch (error) {
      console.error(error);
      throw error;
    } finally {
      removeOverlaySpinner();
    }
  },
})($placeOrder),
]);
```

2024-11-11 11:19 UTC, mcocapiza commented
The `ServerError` configurations are the following ones:
- onRetry?: () => void; /* what to do in case of retry */
- onServerError?: (error: string) => void; /* what to do in case of a server error */

2024-11-11 11:21 UTC, mcocapiza commented
Please update the `ShippingMethods` example (I missed to import the `cartApi` from Cart dropin): 

```
import * as cartApi from '@dropins/storefront-cart/api.js';
import ShippingMethods from '@dropins/storefront-checkout/containers/ShippingMethods.js';
import { render as CheckoutProvider } from '@dropins/storefront-checkout/render.js';

const $delivery = checkoutFragment.querySelector('.checkout__delivery');

CheckoutProvider.render(ShippingMethods, {
  hideOnVirtualCart: true,
  onCheckoutDataUpdate: () => {
    cartApi.refreshCart().catch(console.error);
  },
})($delivery),
```

2024-11-11 11:30 UTC, mcocapiza commented
The `ShippingMethods` configurations are the following ones:
- onCheckoutDataUpdate?: () => Promise<void>; /* what to do in case the checkout data has been updated */
- onShippingMethodSelect?: (method: ShippingMethod) => void; /* what to do in case a shipping method has been selected */
- preSelectedMethod?: { carrierCode: string; methodCode: string }; /* if we want to preselect a specific shipping method */
- shippingMethodsSlot?: SlotProps; /* to provide more shipping methods */

Also we could include another prop:
- hideOnVirtualCart: boolean No Hides the container if the cart is virtual.

2024-11-11 15:09 UTC, jeff-matthews commented
Thanks @mcocapiza. All revisions applied.

2024-11-11 18:28 UTC, keharper approved these changes

2024-11-11 18:33 UTC, merged